

import java.awt.*;
import java.io.*;
import java.util.ArrayList;
import java.util.List;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Zainab
 */
public class Comparison extends javax.swing.JFrame {

    /**
     * Creates new form Comparison
     */
    private List<SchedulingResult> results;
    

     public Comparison(String filePath) {
        initComponents();
        setVisible(true);
        results = new ArrayList<>();
        readDataFromFile(filePath);
        addBarChartsToPanel();
    }

    private void readDataFromFile(String filePath) {
        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] tokens = line.split(",");
                String methodName = tokens[0];
                double avgWaitingTime = Double.parseDouble(tokens[1]);
                double avgTurnaroundTime = Double.parseDouble(tokens[2]);
                results.add(new SchedulingResult(methodName, avgWaitingTime, avgTurnaroundTime));
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    private void addBarChartsToPanel() {
        ComparisonChart comparisonChart = new ComparisonChart(results);
        comparisonchartpanel.removeAll(); // Remove any existing components from the panel
        comparisonchartpanel.setLayout(new BorderLayout());
        comparisonchartpanel.add(comparisonChart, BorderLayout.CENTER); // Add the ComparisonChart to the center
        comparisonchartpanel.revalidate(); // Update the panel layout
        comparisonchartpanel.repaint(); // Repaint the panel to reflect changes
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comparisonchartpanel = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar7 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comparisonchartpanel.setBackground(new java.awt.Color(182, 198, 190));

        javax.swing.GroupLayout comparisonchartpanelLayout = new javax.swing.GroupLayout(comparisonchartpanel);
        comparisonchartpanel.setLayout(comparisonchartpanelLayout);
        comparisonchartpanelLayout.setHorizontalGroup(
            comparisonchartpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        comparisonchartpanelLayout.setVerticalGroup(
            comparisonchartpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(comparisonchartpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 1110, 700));

        jLabel2.setBackground(new java.awt.Color(182, 198, 190));
        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(209, 142, 123));
        jLabel2.setText("COMPARISON OF ALGORITHMS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1200, 840));
        jLabel1.setMinimumSize(new java.awt.Dimension(1200, 840));
        jLabel1.setPreferredSize(new java.awt.Dimension(1200, 840));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 840));

        jMenuBar7.setBackground(new java.awt.Color(182, 198, 190));
        jMenuBar7.setForeground(new java.awt.Color(209, 142, 123));

        jMenu7.setBackground(new java.awt.Color(182, 198, 190));
        jMenu7.setForeground(new java.awt.Color(209, 142, 123));
        jMenu7.setText("Back");

        jMenuItem7.setBackground(new java.awt.Color(182, 198, 190));
        jMenuItem7.setForeground(new java.awt.Color(209, 142, 123));
        jMenuItem7.setText("Back");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem7);

        jMenuBar7.add(jMenu7);

        setJMenuBar(jMenuBar7);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // Close the current FCFS window
        Main main = new Main();
        setVisible(false);
        main.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel comparisonchartpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuBar jMenuBar7;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    // End of variables declaration//GEN-END:variables
}
