
import java.awt.BorderLayout;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Zainab
 */
public class RoundRobin extends javax.swing.JFrame {

    /**
     * Creates new form RoundRobin
     */
    
    private List<Process> processes;
    private ArrayList<GanttRecord> gantt;
    private Queue<Process> readyQueue;
    private int quantumTime;
    private int currentTime;
    private double avgWaitingTime;
    private double avgTurnaroundTime;
    
    public RoundRobin(List<Process> processes) {
        initComponents();
        setVisible(true);
        this.processes = processes;
        gantt = new ArrayList<>();
        readyQueue = new LinkedList<>();
        processes.sort(Comparator.comparingInt(Process::getArrivalTime));
        for (Process process : processes) {
            readyQueue.offer(process); 
        }
        currentTime = 0;
        avgWaitingTime = 0;
        avgTurnaroundTime = 0;
    }

    public void schedule() {
        int totalProcesses = readyQueue.size();
        int totalWaitingTime = 0;
        int totalTurnaroundTime = 0;

        while (!readyQueue.isEmpty()) {
            Process currentProcess = readyQueue.poll();
            int startTime = Math.max(currentTime, currentProcess.getArrivalTime());
            int remainingBurstTime = currentProcess.getRemainingBurstTime();

            int executionTime = Math.min(quantumTime, remainingBurstTime);
            currentTime = startTime + executionTime;
            remainingBurstTime -= executionTime;

            gantt.add(new GanttRecord(startTime, currentTime, currentProcess.getPid()));

            if (remainingBurstTime > 0) {
                currentProcess.setRemainingBurstTime(remainingBurstTime);
                readyQueue.offer(currentProcess);
            } else {
                int waitingTime = currentTime - currentProcess.getArrivalTime() - currentProcess.getCpuBurst();
                int turnaroundTime = currentTime - currentProcess.getArrivalTime();
                currentProcess.setWaitingTime(waitingTime);
                currentProcess.setTurnaroundTime(turnaroundTime);

                totalWaitingTime += waitingTime;
                totalTurnaroundTime += turnaroundTime;
            }
        }

        avgWaitingTime = (double) totalWaitingTime / totalProcesses;
        avgTurnaroundTime = (double) totalTurnaroundTime / totalProcesses;

        try (BufferedWriter writer = new BufferedWriter(new FileWriter("algorithm_results.txt", true))) {
            writer.write("Round Robin" + "," + avgTurnaroundTime + "," + avgWaitingTime);
            writer.newLine();
        } catch (IOException e) {
            e.printStackTrace();
        }
        waittime.setText(Double.toString(avgWaitingTime));
        turnaroundtime.setText(Double.toString(avgTurnaroundTime));

        Display_Proccess process_panel = new Display_Proccess(processes);
        processpanel.removeAll();
        processpanel.setLayout(new BorderLayout());
        processpanel.add(process_panel, BorderLayout.CENTER);
        processpanel.revalidate();
        processpanel.repaint();

        Gantt ganttChart = new Gantt(gantt);
        ganttchartpanel.removeAll();
        ganttchartpanel.setLayout(new BorderLayout());
        ganttchartpanel.add(ganttChart, BorderLayout.CENTER);
        ganttchartpanel.revalidate();
        ganttchartpanel.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        processpanel = new java.awt.Panel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        quantumtime = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        turnaroundtime = new javax.swing.JTextField();
        waittime = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ganttchartpanel = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(182, 198, 190));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        processpanel.setBackground(new java.awt.Color(182, 198, 190));

        javax.swing.GroupLayout processpanelLayout = new javax.swing.GroupLayout(processpanel);
        processpanel.setLayout(processpanelLayout);
        processpanelLayout.setHorizontalGroup(
            processpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        processpanelLayout.setVerticalGroup(
            processpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        getContentPane().add(processpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 1120, 260));

        jLabel7.setBackground(new java.awt.Color(182, 198, 190));
        jLabel7.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(88, 138, 151));
        jLabel7.setText("Processes:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jButton2.setBackground(new java.awt.Color(209, 142, 123));
        jButton2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(210, 227, 234));
        jButton2.setText("Select");
        jButton2.setToolTipText("");
        jButton2.setBorder(null);
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 90, 30));

        quantumtime.setBackground(new java.awt.Color(182, 198, 190));
        quantumtime.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 20)); // NOI18N
        quantumtime.setForeground(new java.awt.Color(209, 142, 123));
        quantumtime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        quantumtime.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        quantumtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantumtimeActionPerformed(evt);
            }
        });
        getContentPane().add(quantumtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 130, 30));

        jLabel6.setBackground(new java.awt.Color(182, 198, 190));
        jLabel6.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(88, 138, 151));
        jLabel6.setText("Quantum Time: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel2.setBackground(new java.awt.Color(182, 198, 190));
        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 60)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(209, 142, 123));
        jLabel2.setText("ROUND ROBIN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        jLabel5.setBackground(new java.awt.Color(182, 198, 190));
        jLabel5.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(88, 138, 151));
        jLabel5.setText("Average Turnaround Time:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 660, -1, -1));

        turnaroundtime.setEditable(false);
        turnaroundtime.setBackground(new java.awt.Color(182, 198, 190));
        turnaroundtime.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 20)); // NOI18N
        turnaroundtime.setForeground(new java.awt.Color(209, 142, 123));
        turnaroundtime.setBorder(null);
        turnaroundtime.setRequestFocusEnabled(false);
        turnaroundtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnaroundtimeActionPerformed(evt);
            }
        });
        getContentPane().add(turnaroundtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 690, 370, -1));

        waittime.setEditable(false);
        waittime.setBackground(new java.awt.Color(182, 198, 190));
        waittime.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 20)); // NOI18N
        waittime.setForeground(new java.awt.Color(209, 142, 123));
        waittime.setBorder(null);
        waittime.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        waittime.setRequestFocusEnabled(false);
        waittime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waittimeActionPerformed(evt);
            }
        });
        getContentPane().add(waittime, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 690, 370, -1));

        jLabel4.setBackground(new java.awt.Color(182, 198, 190));
        jLabel4.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(88, 138, 151));
        jLabel4.setText("Gantt Chart:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jLabel3.setBackground(new java.awt.Color(182, 198, 190));
        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(88, 138, 151));
        jLabel3.setText("Average Wait Time:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 660, -1, -1));

        ganttchartpanel.setBackground(new java.awt.Color(182, 198, 190));

        javax.swing.GroupLayout ganttchartpanelLayout = new javax.swing.GroupLayout(ganttchartpanel);
        ganttchartpanel.setLayout(ganttchartpanelLayout);
        ganttchartpanelLayout.setHorizontalGroup(
            ganttchartpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ganttchartpanelLayout.setVerticalGroup(
            ganttchartpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(ganttchartpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 1110, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bg.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(1200, 840));
        jLabel1.setMinimumSize(new java.awt.Dimension(1200, 840));
        jLabel1.setPreferredSize(new java.awt.Dimension(1200, 840));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 840));

        jMenuBar5.setBackground(new java.awt.Color(182, 198, 190));
        jMenuBar5.setForeground(new java.awt.Color(209, 142, 123));

        jMenu5.setBackground(new java.awt.Color(182, 198, 190));
        jMenu5.setForeground(new java.awt.Color(209, 142, 123));
        jMenu5.setText("Back");

        jMenuItem5.setBackground(new java.awt.Color(182, 198, 190));
        jMenuItem5.setForeground(new java.awt.Color(209, 142, 123));
        jMenuItem5.setText("Back");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuBar5.add(jMenu5);

        setJMenuBar(jMenuBar5);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void turnaroundtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnaroundtimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_turnaroundtimeActionPerformed

    private void waittimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waittimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_waittimeActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        //TODO add your handling code here:

        // Make the original Main window visible
        Main main = new Main();
        setVisible(false);
        main.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void quantumtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantumtimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantumtimeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String quantumTimeString = quantumtime.getText();

        // Convert the string to an integer if needed
        try {
            quantumTime = Integer.parseInt(quantumTimeString);
            // Now you have the timeQuantum value to use
        } catch (NumberFormatException e) {
            // Handle the case where the input is not a valid integer
            JOptionPane.showMessageDialog(null, "Please enter a valid integer for the quantum time.");
        }
        schedule();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel ganttchartpanel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuItem jMenuItem5;
    private java.awt.Panel processpanel;
    private javax.swing.JTextField quantumtime;
    private javax.swing.JTextField turnaroundtime;
    private javax.swing.JTextField waittime;
    // End of variables declaration//GEN-END:variables
}
